### ISSUE TITLE
Protobuf serializer/deserializer

### ISSUE THREAD

**Issue by niffler92** [DisasterAWARE/aws-glue-schema-registry-python#15]
Hi, thank you for your work on this - is there any support on protobuf serializer/deserializer? Or was wondering what it takes to use protobuf with this project.

**Comment by nickzandbergen** [comment]
Protobuf is unsupported. You'd need to do the following:
1. Create a schema
2. Create a serializer/deserializer for it.

**Comment by eliothxchan** [comment]
Is there any intention on adding support for this given that Protobufs are officially supported by AWS Glue now?

**Comment by nickzandbergen** [comment]
Not on my end. Generally speaking, there's no additional feature development planned, since this package currently meets all of DisasterAWARE's requirements.

I'm happy to review PRs though.

**Comment by runeglom** [comment]
Hi, as the need for protobuf V3 support has popped up on our end, we have started the PR
https://github.com/DisasterAWARE/aws-glue-schema-registry-python/pull/29

We are grateful for any review and happy to discuss changes or improvements 😄
