### ISSUE TITLE
Issue with using a schema already present on AWS Glue

### ISSUE THREAD

**Issue by GianniEgo** [DisasterAWARE/aws-glue-schema-registry-python#18]
Good morning,
I'm trying to implement a project that would need this library to work. However, I encountered an error, unlike the example you showed, I extract the schema, which I use for Kafka messages, directly from AWS Glue, I don't take the schema from a file or somewhere else. This means that when I pass the schema to the producer to send it with the message to Kafka, the schema should not be registered again on AWS Glue because it is already present, in fact I extracted it from there previously. Instead what happens is that even if the schema is already present on AWS Glue, another one is registered with the name: "[topic name]-value". If I force my project not to create a new schema by not giving permissions to create it, I get an error creating the schema called as above.
I would like to understand if I am doing something wrong or if this library does not provide the possibility of using patterns already present on AWS without having to register another one with a pattern name described above.

Thank you

Gianni

**Comment by nickzandbergen** [comment]
That's the default library behavior. Providing a schema naming strategy in the KafkaSerializer or your own serializer class changes it.
