### ISSUE TITLE
Implementing json schema support

### ISSUE THREAD

**Issue by Ronserruya** [DisasterAWARE/aws-glue-schema-registry-python#5]
Hey @cdebost , thank you for your work on this pkg :)
We ([lushateam](https://github.com/LushaTeam)) are thinking of using it but we will probably need jsonschema support
Can I submit a pr implementing it? Just want to make sure you are open to it before I start working on it

**Comment by cdebost** [comment]
Hi @Ronserruya, I'll gladly review and release jsonschema support if you submit a PR.

**Comment by cdebost** [comment]
Released at https://pypi.org/project/aws-glue-schema-registry/1.1.0/
